<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AccomodationDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('accomodation_detail')->insert([

            // ================= KUALA LUMPUR =================
            [
                'accomodation_id' => 1,
                'information_place' => 'Luxury studio in Kuala Lumpur city center',
                'img_1' => 'https://picsum.photos/seed/kl1/600/400',
                'img_2' => 'https://picsum.photos/seed/kl2/600/400',
                'img_3' => 'https://picsum.photos/seed/kl3/600/400',
                'img_4' => 'https://picsum.photos/seed/kl4/600/400',
                'img_5' => 'https://picsum.photos/seed/kl5/600/400',
                'hotel_name' => 'KL City Luxury Stay',
                'country' => 'Malaysia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.8,
                'review' => 120,
                'img_host' => 'https://picsum.photos/seed/host1/100',
                'host_name' => 'Ahmad',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Pool, AC, Parking',
                'bedroom_img1' => 'https://picsum.photos/seed/bed1/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed2/400/300',
                'price' => 1200000,
                'time' => 'per night'
            ],

            [
                'accomodation_id' => 2,
                'information_place' => 'Modern apartment near KLCC',
                'img_1' => 'https://picsum.photos/seed/kl6/600/400',
                'img_2' => 'https://picsum.photos/seed/kl7/600/400',
                'img_3' => 'https://picsum.photos/seed/kl8/600/400',
                'img_4' => 'https://picsum.photos/seed/kl9/600/400',
                'img_5' => 'https://picsum.photos/seed/kl10/600/400',
                'hotel_name' => 'KL Modern Suite',
                'country' => 'Malaysia',
                'guest' => '2 guests',
                'bedroom' => '1 bedroom',
                'bed' => '1 bed',
                'bath' => '1 bathroom',
                'rate' => 4.7,
                'review' => 98,
                'img_host' => 'https://picsum.photos/seed/host2/100',
                'host_name' => 'Siti',
                'time_join' => '2 years ago',
                'fasility' => 'Wifi, Gym, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed3/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed4/400/300',
                'price' => 950000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 3,
                'information_place' => 'Luxury studio in Kuala Lumpur city center',
                'img_1' => 'https://picsum.photos/seed/kl1/600/400',
                'img_2' => 'https://picsum.photos/seed/kl2/600/400',
                'img_3' => 'https://picsum.photos/seed/kl3/600/400',
                'img_4' => 'https://picsum.photos/seed/kl4/600/400',
                'img_5' => 'https://picsum.photos/seed/kl5/600/400',
                'hotel_name' => 'KL City Luxury Stay',
                'country' => 'Malaysia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.8,
                'review' => 120,
                'img_host' => 'https://picsum.photos/seed/host1/100',
                'host_name' => 'Ahmad',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Pool, AC, Parking',
                'bedroom_img1' => 'https://picsum.photos/seed/bed1/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed2/400/300',
                'price' => 1200000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 4,
                'information_place' => 'Luxury studio in Kuala Lumpur city center',
                'img_1' => 'https://picsum.photos/seed/kl1/600/400',
                'img_2' => 'https://picsum.photos/seed/kl2/600/400',
                'img_3' => 'https://picsum.photos/seed/kl3/600/400',
                'img_4' => 'https://picsum.photos/seed/kl4/600/400',
                'img_5' => 'https://picsum.photos/seed/kl5/600/400',
                'hotel_name' => 'KL City Luxury Stay',
                'country' => 'Malaysia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.8,
                'review' => 120,
                'img_host' => 'https://picsum.photos/seed/host1/100',
                'host_name' => 'Ahmad',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Pool, AC, Parking',
                'bedroom_img1' => 'https://picsum.photos/seed/bed1/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed2/400/300',
                'price' => 1200000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 5,
                'information_place' => 'Luxury studio in Kuala Lumpur city center',
                'img_1' => 'https://picsum.photos/seed/kl1/600/400',
                'img_2' => 'https://picsum.photos/seed/kl2/600/400',
                'img_3' => 'https://picsum.photos/seed/kl3/600/400',
                'img_4' => 'https://picsum.photos/seed/kl4/600/400',
                'img_5' => 'https://picsum.photos/seed/kl5/600/400',
                'hotel_name' => 'KL City Luxury Stay',
                'country' => 'Malaysia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.8,
                'review' => 120,
                'img_host' => 'https://picsum.photos/seed/host1/100',
                'host_name' => 'Ahmad',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Pool, AC, Parking',
                'bedroom_img1' => 'https://picsum.photos/seed/bed1/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed2/400/300',
                'price' => 1200000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 6,
                'information_place' => 'Luxury studio in Kuala Lumpur city center',
                'img_1' => 'https://picsum.photos/seed/kl1/600/400',
                'img_2' => 'https://picsum.photos/seed/kl2/600/400',
                'img_3' => 'https://picsum.photos/seed/kl3/600/400',
                'img_4' => 'https://picsum.photos/seed/kl4/600/400',
                'img_5' => 'https://picsum.photos/seed/kl5/600/400',
                'hotel_name' => 'KL City Luxury Stay',
                'country' => 'Malaysia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.8,
                'review' => 120,
                'img_host' => 'https://picsum.photos/seed/host1/100',
                'host_name' => 'Ahmad',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Pool, AC, Parking',
                'bedroom_img1' => 'https://picsum.photos/seed/bed1/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed2/400/300',
                'price' => 1200000,
                'time' => 'per night'
            ],

            // ================= JAKARTA =================
            [
                'accomodation_id' => 7,
                'information_place' => 'Central Jakarta apartment near Sudirman',
                'img_1' => 'https://picsum.photos/seed/jkt1/600/400',
                'img_2' => 'https://picsum.photos/seed/jkt2/600/400',
                'img_3' => 'https://picsum.photos/seed/jkt3/600/400',
                'img_4' => 'https://picsum.photos/seed/jkt4/600/400',
                'img_5' => 'https://picsum.photos/seed/jkt5/600/400',
                'hotel_name' => 'Jakarta City Stay',
                'country' => 'Indonesia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.6,
                'review' => 110,
                'img_host' => 'https://picsum.photos/seed/host3/100',
                'host_name' => 'Budi',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Parking, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed5/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed6/400/300',
                'price' => 1000000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 8,
                'information_place' => 'Central Jakarta apartment near Sudirman',
                'img_1' => 'https://picsum.photos/seed/jkt1/600/400',
                'img_2' => 'https://picsum.photos/seed/jkt2/600/400',
                'img_3' => 'https://picsum.photos/seed/jkt3/600/400',
                'img_4' => 'https://picsum.photos/seed/jkt4/600/400',
                'img_5' => 'https://picsum.photos/seed/jkt5/600/400',
                'hotel_name' => 'Jakarta City Stay',
                'country' => 'Indonesia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.6,
                'review' => 110,
                'img_host' => 'https://picsum.photos/seed/host3/100',
                'host_name' => 'Budi',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Parking, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed5/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed6/400/300',
                'price' => 1000000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 9,
                'information_place' => 'Central Jakarta apartment near Sudirman',
                'img_1' => 'https://picsum.photos/seed/jkt1/600/400',
                'img_2' => 'https://picsum.photos/seed/jkt2/600/400',
                'img_3' => 'https://picsum.photos/seed/jkt3/600/400',
                'img_4' => 'https://picsum.photos/seed/jkt4/600/400',
                'img_5' => 'https://picsum.photos/seed/jkt5/600/400',
                'hotel_name' => 'Jakarta City Stay',
                'country' => 'Indonesia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.6,
                'review' => 110,
                'img_host' => 'https://picsum.photos/seed/host3/100',
                'host_name' => 'Budi',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Parking, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed5/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed6/400/300',
                'price' => 1000000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 10,
                'information_place' => 'Central Jakarta apartment near Sudirman',
                'img_1' => 'https://picsum.photos/seed/jkt1/600/400',
                'img_2' => 'https://picsum.photos/seed/jkt2/600/400',
                'img_3' => 'https://picsum.photos/seed/jkt3/600/400',
                'img_4' => 'https://picsum.photos/seed/jkt4/600/400',
                'img_5' => 'https://picsum.photos/seed/jkt5/600/400',
                'hotel_name' => 'Jakarta City Stay',
                'country' => 'Indonesia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.6,
                'review' => 110,
                'img_host' => 'https://picsum.photos/seed/host3/100',
                'host_name' => 'Budi',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Parking, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed5/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed6/400/300',
                'price' => 1000000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 11,
                'information_place' => 'Central Jakarta apartment near Sudirman',
                'img_1' => 'https://picsum.photos/seed/jkt1/600/400',
                'img_2' => 'https://picsum.photos/seed/jkt2/600/400',
                'img_3' => 'https://picsum.photos/seed/jkt3/600/400',
                'img_4' => 'https://picsum.photos/seed/jkt4/600/400',
                'img_5' => 'https://picsum.photos/seed/jkt5/600/400',
                'hotel_name' => 'Jakarta City Stay',
                'country' => 'Indonesia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.6,
                'review' => 110,
                'img_host' => 'https://picsum.photos/seed/host3/100',
                'host_name' => 'Budi',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Parking, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed5/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed6/400/300',
                'price' => 1000000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 12,
                'information_place' => 'Central Jakarta apartment near Sudirman',
                'img_1' => 'https://picsum.photos/seed/jkt1/600/400',
                'img_2' => 'https://picsum.photos/seed/jkt2/600/400',
                'img_3' => 'https://picsum.photos/seed/jkt3/600/400',
                'img_4' => 'https://picsum.photos/seed/jkt4/600/400',
                'img_5' => 'https://picsum.photos/seed/jkt5/600/400',
                'hotel_name' => 'Jakarta City Stay',
                'country' => 'Indonesia',
                'guest' => '3 guests',
                'bedroom' => '1 bedroom',
                'bed' => '2 beds',
                'bath' => '1 bathroom',
                'rate' => 4.6,
                'review' => 110,
                'img_host' => 'https://picsum.photos/seed/host3/100',
                'host_name' => 'Budi',
                'time_join' => '1 year ago',
                'fasility' => 'Wifi, Parking, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed5/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed6/400/300',
                'price' => 1000000,
                'time' => 'per night'
            ],

            // ================= TOKYO =================
            [
                'accomodation_id' => 13,
                'information_place' => 'Minimalist apartment in Tokyo',
                'img_1' => 'https://picsum.photos/seed/tokyo1/600/400',
                'img_2' => 'https://picsum.photos/seed/tokyo2/600/400',
                'img_3' => 'https://picsum.photos/seed/tokyo3/600/400',
                'img_4' => 'https://picsum.photos/seed/tokyo4/600/400',
                'img_5' => 'https://picsum.photos/seed/tokyo5/600/400',
                'hotel_name' => 'Tokyo Urban Stay',
                'country' => 'Japan',
                'guest' => '2 guests',
                'bedroom' => '1 bedroom',
                'bed' => '1 bed',
                'bath' => '1 bathroom',
                'rate' => 4.9,
                'review' => 150,
                'img_host' => 'https://picsum.photos/seed/host4/100',
                'host_name' => 'Hiroshi',
                'time_join' => '3 years ago',
                'fasility' => 'Wifi, Heating, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed7/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed8/400/300',
                'price' => 1800000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 14,
                'information_place' => 'Minimalist apartment in Tokyo',
                'img_1' => 'https://picsum.photos/seed/tokyo1/600/400',
                'img_2' => 'https://picsum.photos/seed/tokyo2/600/400',
                'img_3' => 'https://picsum.photos/seed/tokyo3/600/400',
                'img_4' => 'https://picsum.photos/seed/tokyo4/600/400',
                'img_5' => 'https://picsum.photos/seed/tokyo5/600/400',
                'hotel_name' => 'Tokyo Urban Stay',
                'country' => 'Japan',
                'guest' => '2 guests',
                'bedroom' => '1 bedroom',
                'bed' => '1 bed',
                'bath' => '1 bathroom',
                'rate' => 4.9,
                'review' => 150,
                'img_host' => 'https://picsum.photos/seed/host4/100',
                'host_name' => 'Hiroshi',
                'time_join' => '3 years ago',
                'fasility' => 'Wifi, Heating, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed7/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed8/400/300',
                'price' => 1800000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 15,
                'information_place' => 'Minimalist apartment in Tokyo',
                'img_1' => 'https://picsum.photos/seed/tokyo1/600/400',
                'img_2' => 'https://picsum.photos/seed/tokyo2/600/400',
                'img_3' => 'https://picsum.photos/seed/tokyo3/600/400',
                'img_4' => 'https://picsum.photos/seed/tokyo4/600/400',
                'img_5' => 'https://picsum.photos/seed/tokyo5/600/400',
                'hotel_name' => 'Tokyo Urban Stay',
                'country' => 'Japan',
                'guest' => '2 guests',
                'bedroom' => '1 bedroom',
                'bed' => '1 bed',
                'bath' => '1 bathroom',
                'rate' => 4.9,
                'review' => 150,
                'img_host' => 'https://picsum.photos/seed/host4/100',
                'host_name' => 'Hiroshi',
                'time_join' => '3 years ago',
                'fasility' => 'Wifi, Heating, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed7/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed8/400/300',
                'price' => 1800000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 16,
                'information_place' => 'Minimalist apartment in Tokyo',
                'img_1' => 'https://picsum.photos/seed/tokyo1/600/400',
                'img_2' => 'https://picsum.photos/seed/tokyo2/600/400',
                'img_3' => 'https://picsum.photos/seed/tokyo3/600/400',
                'img_4' => 'https://picsum.photos/seed/tokyo4/600/400',
                'img_5' => 'https://picsum.photos/seed/tokyo5/600/400',
                'hotel_name' => 'Tokyo Urban Stay',
                'country' => 'Japan',
                'guest' => '2 guests',
                'bedroom' => '1 bedroom',
                'bed' => '1 bed',
                'bath' => '1 bathroom',
                'rate' => 4.9,
                'review' => 150,
                'img_host' => 'https://picsum.photos/seed/host4/100',
                'host_name' => 'Hiroshi',
                'time_join' => '3 years ago',
                'fasility' => 'Wifi, Heating, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed7/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed8/400/300',
                'price' => 1800000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 17,
                'information_place' => 'Minimalist apartment in Tokyo',
                'img_1' => 'https://picsum.photos/seed/tokyo1/600/400',
                'img_2' => 'https://picsum.photos/seed/tokyo2/600/400',
                'img_3' => 'https://picsum.photos/seed/tokyo3/600/400',
                'img_4' => 'https://picsum.photos/seed/tokyo4/600/400',
                'img_5' => 'https://picsum.photos/seed/tokyo5/600/400',
                'hotel_name' => 'Tokyo Urban Stay',
                'country' => 'Japan',
                'guest' => '2 guests',
                'bedroom' => '1 bedroom',
                'bed' => '1 bed',
                'bath' => '1 bathroom',
                'rate' => 4.9,
                'review' => 150,
                'img_host' => 'https://picsum.photos/seed/host4/100',
                'host_name' => 'Hiroshi',
                'time_join' => '3 years ago',
                'fasility' => 'Wifi, Heating, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed7/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed8/400/300',
                'price' => 1800000,
                'time' => 'per night'
            ],
            [
                'accomodation_id' => 18,
                'information_place' => 'Minimalist apartment in Tokyo',
                'img_1' => 'https://picsum.photos/seed/tokyo1/600/400',
                'img_2' => 'https://picsum.photos/seed/tokyo2/600/400',
                'img_3' => 'https://picsum.photos/seed/tokyo3/600/400',
                'img_4' => 'https://picsum.photos/seed/tokyo4/600/400',
                'img_5' => 'https://picsum.photos/seed/tokyo5/600/400',
                'hotel_name' => 'Tokyo Urban Stay',
                'country' => 'Japan',
                'guest' => '2 guests',
                'bedroom' => '1 bedroom',
                'bed' => '1 bed',
                'bath' => '1 bathroom',
                'rate' => 4.9,
                'review' => 150,
                'img_host' => 'https://picsum.photos/seed/host4/100',
                'host_name' => 'Hiroshi',
                'time_join' => '3 years ago',
                'fasility' => 'Wifi, Heating, AC',
                'bedroom_img1' => 'https://picsum.photos/seed/bed7/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed8/400/300',
                'price' => 1800000,
                'time' => 'per night'
            ],

            // ================= UBUD =================
            [
                'accomodation_id' => 19,
                'information_place' => 'Villa with jungle view in Ubud',
                'img_1' => 'https://picsum.photos/seed/ubud1/600/400',
                'img_2' => 'https://picsum.photos/seed/ubud2/600/400',
                'img_3' => 'https://picsum.photos/seed/ubud3/600/400',
                'img_4' => 'https://picsum.photos/seed/ubud4/600/400',
                'img_5' => 'https://picsum.photos/seed/ubud5/600/400',
                'hotel_name' => 'Ubud Nature Villa',
                'country' => 'Indonesia',
                'guest' => '4 guests',
                'bedroom' => '2 bedroom',
                'bed' => '2 beds',
                'bath' => '2 bathroom',
                'rate' => 4.9,
                'review' => 200,
                'img_host' => 'https://picsum.photos/seed/host5/100',
                'host_name' => 'Made',
                'time_join' => '5 years ago',
                'fasility' => 'Pool, Wifi, Garden',
                'bedroom_img1' => 'https://picsum.photos/seed/bed9/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed10/400/300',
                'price' => 1500000,
                'time' => 'per night'
            ],
             [
                'accomodation_id' => 20,
                'information_place' => 'Villa with jungle view in Ubud',
                'img_1' => 'https://picsum.photos/seed/ubud1/600/400',
                'img_2' => 'https://picsum.photos/seed/ubud2/600/400',
                'img_3' => 'https://picsum.photos/seed/ubud3/600/400',
                'img_4' => 'https://picsum.photos/seed/ubud4/600/400',
                'img_5' => 'https://picsum.photos/seed/ubud5/600/400',
                'hotel_name' => 'Ubud Nature Villa',
                'country' => 'Indonesia',
                'guest' => '4 guests',
                'bedroom' => '2 bedroom',
                'bed' => '2 beds',
                'bath' => '2 bathroom',
                'rate' => 4.9,
                'review' => 200,
                'img_host' => 'https://picsum.photos/seed/host5/100',
                'host_name' => 'Made',
                'time_join' => '5 years ago',
                'fasility' => 'Pool, Wifi, Garden',
                'bedroom_img1' => 'https://picsum.photos/seed/bed9/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed10/400/300',
                'price' => 1500000,
                'time' => 'per night'
            ],
             [
                'accomodation_id' => 21,
                'information_place' => 'Villa with jungle view in Ubud',
                'img_1' => 'https://picsum.photos/seed/ubud1/600/400',
                'img_2' => 'https://picsum.photos/seed/ubud2/600/400',
                'img_3' => 'https://picsum.photos/seed/ubud3/600/400',
                'img_4' => 'https://picsum.photos/seed/ubud4/600/400',
                'img_5' => 'https://picsum.photos/seed/ubud5/600/400',
                'hotel_name' => 'Ubud Nature Villa',
                'country' => 'Indonesia',
                'guest' => '4 guests',
                'bedroom' => '2 bedroom',
                'bed' => '2 beds',
                'bath' => '2 bathroom',
                'rate' => 4.9,
                'review' => 200,
                'img_host' => 'https://picsum.photos/seed/host5/100',
                'host_name' => 'Made',
                'time_join' => '5 years ago',
                'fasility' => 'Pool, Wifi, Garden',
                'bedroom_img1' => 'https://picsum.photos/seed/bed9/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed10/400/300',
                'price' => 1500000,
                'time' => 'per night'
            ],
             [
                'accomodation_id' => 22,
                'information_place' => 'Villa with jungle view in Ubud',
                'img_1' => 'https://picsum.photos/seed/ubud1/600/400',
                'img_2' => 'https://picsum.photos/seed/ubud2/600/400',
                'img_3' => 'https://picsum.photos/seed/ubud3/600/400',
                'img_4' => 'https://picsum.photos/seed/ubud4/600/400',
                'img_5' => 'https://picsum.photos/seed/ubud5/600/400',
                'hotel_name' => 'Ubud Nature Villa',
                'country' => 'Indonesia',
                'guest' => '4 guests',
                'bedroom' => '2 bedroom',
                'bed' => '2 beds',
                'bath' => '2 bathroom',
                'rate' => 4.9,
                'review' => 200,
                'img_host' => 'https://picsum.photos/seed/host5/100',
                'host_name' => 'Made',
                'time_join' => '5 years ago',
                'fasility' => 'Pool, Wifi, Garden',
                'bedroom_img1' => 'https://picsum.photos/seed/bed9/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed10/400/300',
                'price' => 1500000,
                'time' => 'per night'
            ],
             [
                'accomodation_id' => 23,
                'information_place' => 'Villa with jungle view in Ubud',
                'img_1' => 'https://picsum.photos/seed/ubud1/600/400',
                'img_2' => 'https://picsum.photos/seed/ubud2/600/400',
                'img_3' => 'https://picsum.photos/seed/ubud3/600/400',
                'img_4' => 'https://picsum.photos/seed/ubud4/600/400',
                'img_5' => 'https://picsum.photos/seed/ubud5/600/400',
                'hotel_name' => 'Ubud Nature Villa',
                'country' => 'Indonesia',
                'guest' => '4 guests',
                'bedroom' => '2 bedroom',
                'bed' => '2 beds',
                'bath' => '2 bathroom',
                'rate' => 4.9,
                'review' => 200,
                'img_host' => 'https://picsum.photos/seed/host5/100',
                'host_name' => 'Made',
                'time_join' => '5 years ago',
                'fasility' => 'Pool, Wifi, Garden',
                'bedroom_img1' => 'https://picsum.photos/seed/bed9/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed10/400/300',
                'price' => 1500000,
                'time' => 'per night'
            ],
             [
                'accomodation_id' => 24,
                'information_place' => 'Villa with jungle view in Ubud',
                'img_1' => 'https://picsum.photos/seed/ubud1/600/400',
                'img_2' => 'https://picsum.photos/seed/ubud2/600/400',
                'img_3' => 'https://picsum.photos/seed/ubud3/600/400',
                'img_4' => 'https://picsum.photos/seed/ubud4/600/400',
                'img_5' => 'https://picsum.photos/seed/ubud5/600/400',
                'hotel_name' => 'Ubud Nature Villa',
                'country' => 'Indonesia',
                'guest' => '4 guests',
                'bedroom' => '2 bedroom',
                'bed' => '2 beds',
                'bath' => '2 bathroom',
                'rate' => 4.9,
                'review' => 200,
                'img_host' => 'https://picsum.photos/seed/host5/100',
                'host_name' => 'Made',
                'time_join' => '5 years ago',
                'fasility' => 'Pool, Wifi, Garden',
                'bedroom_img1' => 'https://picsum.photos/seed/bed9/400/300',
                'bedroom_img2' => 'https://picsum.photos/seed/bed10/400/300',
                'price' => 1500000,
                'time' => 'per night'
            ],

        ]);
    }
}
