<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServicesDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('services_detail')->insert([
            
            // SPA
            [
                'services_id' => 1,
                'img1' => 'spa1.jpg',
                'img_host' => 'host1.jpg',
                'service_name' => 'Relaxing Spa Bali',
                'description' => 'Enjoy relaxing spa with traditional Balinese technique',
                'information' => 'Professional spa therapist',
                'service' => 'spa',
                'review' => 120,
                'rate' => 4.8,
                'price' => 250000,
                'guest' => 1,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Welcome drink',
                'des_service2' => 'Body massage',
                'des_service3' => 'Aromatherapy',
                'des_service4' => 'Relax session',
                'des_service5' => 'Hot stone',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic spa',
                'service_recomend2' => 'Premium spa',
                'service_recomend3' => 'Couple spa',
                'service_recomend4' => 'Luxury spa',
                'service_recomend5' => 'VIP spa',
                'service_recomend6' => 'Full package',

                'price1' => 250000,
                'price2' => 350000,
                'price3' => 500000,
                'price4' => 700000,
                'price5' => 900000,
                'price6' => 1200000,

                'time' => '2 hours',
                'host_name' => 'Made',

                'my_qualifications1' => 'Certified therapist',
                'my_qualifications2' => '5 years experience',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => 'International certificate',
                'qualification_information2' => 'Handled 100+ clients',
                'qualification_information3' => 'Trusted service',
                'qualification_information4' => 'High quality',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Ubud, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 2,
                'img1' => 'spa1.jpg',
                'img_host' => 'host1.jpg',
                'service_name' => 'Relaxing Spa Bali',
                'description' => 'Enjoy relaxing spa with traditional Balinese technique',
                'information' => 'Professional spa therapist',
                'service' => 'spa',
                'review' => 120,
                'rate' => 4.8,
                'price' => 250000,
                'guest' => 1,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Welcome drink',
                'des_service2' => 'Body massage',
                'des_service3' => 'Aromatherapy',
                'des_service4' => 'Relax session',
                'des_service5' => 'Hot stone',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic spa',
                'service_recomend2' => 'Premium spa',
                'service_recomend3' => 'Couple spa',
                'service_recomend4' => 'Luxury spa',
                'service_recomend5' => 'VIP spa',
                'service_recomend6' => 'Full package',

                'price1' => 250000,
                'price2' => 350000,
                'price3' => 500000,
                'price4' => 700000,
                'price5' => 900000,
                'price6' => 1200000,

                'time' => '2 hours',
                'host_name' => 'Made',

                'my_qualifications1' => 'Certified therapist',
                'my_qualifications2' => '5 years experience',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => 'International certificate',
                'qualification_information2' => 'Handled 100+ clients',
                'qualification_information3' => 'Trusted service',
                'qualification_information4' => 'High quality',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Ubud, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 3,
                'img1' => 'spa1.jpg',
                'img_host' => 'host1.jpg',
                'service_name' => 'Relaxing Spa Bali',
                'description' => 'Enjoy relaxing spa with traditional Balinese technique',
                'information' => 'Professional spa therapist',
                'service' => 'spa',
                'review' => 120,
                'rate' => 4.8,
                'price' => 250000,
                'guest' => 1,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Welcome drink',
                'des_service2' => 'Body massage',
                'des_service3' => 'Aromatherapy',
                'des_service4' => 'Relax session',
                'des_service5' => 'Hot stone',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic spa',
                'service_recomend2' => 'Premium spa',
                'service_recomend3' => 'Couple spa',
                'service_recomend4' => 'Luxury spa',
                'service_recomend5' => 'VIP spa',
                'service_recomend6' => 'Full package',

                'price1' => 250000,
                'price2' => 350000,
                'price3' => 500000,
                'price4' => 700000,
                'price5' => 900000,
                'price6' => 1200000,

                'time' => '2 hours',
                'host_name' => 'Made',

                'my_qualifications1' => 'Certified therapist',
                'my_qualifications2' => '5 years experience',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => 'International certificate',
                'qualification_information2' => 'Handled 100+ clients',
                'qualification_information3' => 'Trusted service',
                'qualification_information4' => 'High quality',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Ubud, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 4,
                'img1' => 'spa1.jpg',
                'img_host' => 'host1.jpg',
                'service_name' => 'Relaxing Spa Bali',
                'description' => 'Enjoy relaxing spa with traditional Balinese technique',
                'information' => 'Professional spa therapist',
                'service' => 'spa',
                'review' => 120,
                'rate' => 4.8,
                'price' => 250000,
                'guest' => 1,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Welcome drink',
                'des_service2' => 'Body massage',
                'des_service3' => 'Aromatherapy',
                'des_service4' => 'Relax session',
                'des_service5' => 'Hot stone',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic spa',
                'service_recomend2' => 'Premium spa',
                'service_recomend3' => 'Couple spa',
                'service_recomend4' => 'Luxury spa',
                'service_recomend5' => 'VIP spa',
                'service_recomend6' => 'Full package',

                'price1' => 250000,
                'price2' => 350000,
                'price3' => 500000,
                'price4' => 700000,
                'price5' => 900000,
                'price6' => 1200000,

                'time' => '2 hours',
                'host_name' => 'Made',

                'my_qualifications1' => 'Certified therapist',
                'my_qualifications2' => '5 years experience',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => 'International certificate',
                'qualification_information2' => 'Handled 100+ clients',
                'qualification_information3' => 'Trusted service',
                'qualification_information4' => 'High quality',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Ubud, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 5,
                'img1' => 'spa1.jpg',
                'img_host' => 'host1.jpg',
                'service_name' => 'Relaxing Spa Bali',
                'description' => 'Enjoy relaxing spa with traditional Balinese technique',
                'information' => 'Professional spa therapist',
                'service' => 'spa',
                'review' => 120,
                'rate' => 4.8,
                'price' => 250000,
                'guest' => 1,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Welcome drink',
                'des_service2' => 'Body massage',
                'des_service3' => 'Aromatherapy',
                'des_service4' => 'Relax session',
                'des_service5' => 'Hot stone',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic spa',
                'service_recomend2' => 'Premium spa',
                'service_recomend3' => 'Couple spa',
                'service_recomend4' => 'Luxury spa',
                'service_recomend5' => 'VIP spa',
                'service_recomend6' => 'Full package',

                'price1' => 250000,
                'price2' => 350000,
                'price3' => 500000,
                'price4' => 700000,
                'price5' => 900000,
                'price6' => 1200000,

                'time' => '2 hours',
                'host_name' => 'Made',

                'my_qualifications1' => 'Certified therapist',
                'my_qualifications2' => '5 years experience',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => 'International certificate',
                'qualification_information2' => 'Handled 100+ clients',
                'qualification_information3' => 'Trusted service',
                'qualification_information4' => 'High quality',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Ubud, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 6,
                'img1' => 'spa1.jpg',
                'img_host' => 'host1.jpg',
                'service_name' => 'Relaxing Spa Bali',
                'description' => 'Enjoy relaxing spa with traditional Balinese technique',
                'information' => 'Professional spa therapist',
                'service' => 'spa',
                'review' => 120,
                'rate' => 4.8,
                'price' => 250000,
                'guest' => 1,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Welcome drink',
                'des_service2' => 'Body massage',
                'des_service3' => 'Aromatherapy',
                'des_service4' => 'Relax session',
                'des_service5' => 'Hot stone',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic spa',
                'service_recomend2' => 'Premium spa',
                'service_recomend3' => 'Couple spa',
                'service_recomend4' => 'Luxury spa',
                'service_recomend5' => 'VIP spa',
                'service_recomend6' => 'Full package',

                'price1' => 250000,
                'price2' => 350000,
                'price3' => 500000,
                'price4' => 700000,
                'price5' => 900000,
                'price6' => 1200000,

                'time' => '2 hours',
                'host_name' => 'Made',

                'my_qualifications1' => 'Certified therapist',
                'my_qualifications2' => '5 years experience',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => 'International certificate',
                'qualification_information2' => 'Handled 100+ clients',
                'qualification_information3' => 'Trusted service',
                'qualification_information4' => 'High quality',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Ubud, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PHOTOGRAPHY
            [
                'services_id' => 7,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 8,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 9,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 10,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 11,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 12,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 13,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 14,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 15,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 16,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 17,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 18,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 19,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 20,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 21,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 22,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 23,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 24,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 25,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 26,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 27,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 28,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 29,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 30,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 31,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 32,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 33,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 34,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 35,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'services_id' => 36,
                'img1' => 'photo1.jpg',
                'img_host' => 'host2.jpg',
                'service_name' => 'Bali Photoshoot',
                'description' => 'Capture your best moment in Bali',
                'information' => 'Professional photographer',
                'service' => 'photography',
                'review' => 90,
                'rate' => 4.9,
                'price' => 800000,
                'guest' => 2,

                'img_service1' => 's1.jpg',
                'img_service2' => 's2.jpg',
                'img_service3' => 's3.jpg',
                'img_service4' => 's4.jpg',
                'img_service5' => 's5.jpg',
                'img_service6' => 's6.jpg',

                'des_service1' => 'Meet up',
                'des_service2' => 'Photoshoot',
                'des_service3' => 'Editing',
                'des_service4' => 'Preview',
                'des_service5' => 'Delivery',
                'des_service6' => 'Finish',

                'service_recomend1' => 'Basic shoot',
                'service_recomend2' => 'Couple shoot',
                'service_recomend3' => 'Prewedding',
                'service_recomend4' => 'Travel shoot',
                'service_recomend5' => 'Luxury shoot',
                'service_recomend6' => 'VIP shoot',

                'price1' => 800000,
                'price2' => 1200000,
                'price3' => 2000000,
                'price4' => 2500000,
                'price5' => 3000000,
                'price6' => 4000000,

                'time' => '3 hours',
                'host_name' => 'Wayan',

                'my_qualifications1' => 'Expert photographer',
                'my_qualifications2' => 'Creative',
                'my_qualifications3' => 'Professional',
                'my_qualifications4' => 'Friendly',

                'qualification_information1' => '10 years experience',
                'qualification_information2' => 'High-end camera',
                'qualification_information3' => 'Trusted',
                'qualification_information4' => 'Fast delivery',

                'img_portofolio1' => 'p1.jpg',
                'img_portofolio2' => 'p2.jpg',
                'img_portofolio3' => 'p3.jpg',

                'address' => 'Kuta, Bali',
                'maps' => 'https://maps.google.com',

                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 👉 Kamu bisa copy pola ini untuk:
            // chef (id:3), sport (4), makeup (5), hair (6)

        ]);
    }
}
